# Generated by Django 4.1.5 on 2023-01-13 11:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_cart_completed_checkout_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, unique=True),
        ),
    ]
