# Generated by Django 4.1.5 on 2023-01-13 11:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_alter_checkout_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, unique=True),
        ),
    ]
