# Generated by Django 4.1.5 on 2023-01-16 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_app', '0006_alter_checkout_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='merchant',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_merchant_carts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutproduct',
            name='merchant',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_merchant_checkoutproducts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
