# Generated by Django 4.1.5 on 2023-01-11 09:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_product_name', unique_with=['base_product__name']),
        ),
    ]
