# Generated by Django 4.1.5 on 2023-01-21 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('superuser', True), ('admin', True), ('staff', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='get_admin_delivery_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_delivery_charge', to='admin_app.district'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='admin_app.category'),
        ),
    ]
