# Generated by Django 4.1.5 on 2023-01-18 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f19d9dfe-d0e1-43f8-bd84-9161ddbf643d'), editable=False),
        ),
    ]
