# Generated by Django 4.1.5 on 2023-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_useraddress_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
